### ISSUE TITLE
Task schedule starving

### ISSUE THREAD

**Issue by claudiucismaru** [gadgetstogrow/TaskScheduler#1]
When a task can run, it breaks the task list iteration and starts over, meaning that one task can starve the others, if the canRun() returns true...

All the tasks should have the chance to see if they can run or not.

**Comment by gadgetstogrow** [comment]
Hi,
It starts over (after a task is run ()) by design to implement a simple priority scheme. Take a look at Alan's (the library's author) blog. This is his way of making sure high priority tasks (first in the array) are given the highest priority. I hope this helps. 
Regards,
Kevin
