### ISSUE TITLE
Include header not found

### ISSUE THREAD

**Issue by elestedt** [gadgetstogrow/TaskScheduler#3]
In `Timer.h` `<arduino.h>` is included. This file does not exist on a linux system - instead it is named <Arduino.h>. Actually it probably is on windows as well, it's just that on windows filenames are case insensitive...

**Comment by gadgetstogrow** [comment]
Hello Fredrik,

You mention Timer.h?  What example are you referring to? Thanks for your feedback.

Regards, 
Kevin

**Comment by elestedt** [comment]
My bad - had multiple windows open and placed the issue on the wrong repository. Sorry for the inconvenience :/
